language: python

python:
- 2.7
- 3.4
- 3.5
- 3.6

script: python setup.py test

notifications:
- email: false

before_deploy:
- python setup.py sdist
- python setup.py bdist_wheel
- python setup.py bdist_wheel --universal
- python setup.py egg_info

deploy:
- provider: pypi
  user: jonathandekhtiar
  password: "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
    
- provider: releases
  file:
  - dist/*
  - python3_linkedin.egg-info/PKG-INFO
  file_glob: true
  skip_cleanup: true
  api_key: "$GITHUB_PERSONAL_TOKEN"
  on:
    tags: true
    python: '3.6'
    
env:
  global:
    ### === PYPI_PASSWORD === ###
    secure: "ZEu1IdaZmGW8Q02K2He1rJhF3HxV3cPXJS8JPNn6l1yt5bkeg8OnYUATe+kXOsORNQtpx25FJfZ7ob3WjsOm/s/+Y0073sV5LXzt0moHgUo93W0zSFf984F3jT06jdEDw8Ta3nDNkLi9KCPG9uaXmGHCR6p8D5TUvhrFFXMqneIodqJUp7o0j4jVlkK+MuFDcighJ38T7+oeWadfcgcS+WIiI14sA+PqYgZZHgITsxRqNQnpWeepUm2TSAXoPo4mUH+U4wQhHHeY1VcBmeyLvnu5lYL7z/ZGaGdWKiu93jjOlU597+nO0bx+q6wYN1eC+YgP7zBiFzXg0Y2mCWspnLIdIuFeNOSlYxx7eLqT/7IrxhGoQnLc+HEqRlWeuCI4guJtF/5y1iQlVbhlD2E9bUppQKKvqesFzrxEg3EXQbphXyrVPmRLLduByVd52PcQnd8pOW9vOhUBZ+b+08OrTRZcFAMfv7YB0CbCOmQkBf+aXeMZk3KMrBxPMouU2cO4QqXDacUqgJL6msAr99KE/2eNqJQPoI1KF4AAaZ8sFIFxto2umj7QHGtF3jUlXaABr3QVH8lUJpPE2xOJd8PRtaItXEZlZsDXhNyztq9CdGHq5nEEUrEiPILWH7qqippCWRcjsFe8yGGUMRkF88KesB1JCGIU74ahQn3avBF1Clc="
    
    ### === GITHUB_PERSONAL_TOKEN === ###
    secure: "OiXyu31cNYoVxpWzxuDdMsr6Vc+BPAUOo4lHsiKtLS7qwaWIAR+CxRfrUmPbA/TCyBvBmKzNTCziWuBvm1hekvO38hOemKNs6PG0o/Jp/aCFGvrIdxp6FlaGwoIweDg+T/1nZ7+jk/UXrUIIEEjgVsBf35M0l9w5ffwoFGA2/bx40Dy//56YQ5coIcghkR+ROpYjhmyoePlcg8IMG8Bqmmyitdcbx3RnJO+UMJSwfXtRqs2svv2W+etMTRpx9brV9BYPM1vPi5DHV7aF0TRYSBrafgVIILw1aaW3UNhhfwAlD+mm2WeSAiqfEuovYUTTg6llJXQGgzAYE3+1vI78jTt2NJcOREC/FDh3VoQVuaNzsxDDgTnUPTiraaLSyR5cqvZp6MsWVPbELNqWpV+/FDEs4pfqtY3BXonoKlIN3SyCgIfjSoItjVeBhQPv/kQ/khQolSZMuvdTKbETuwzWXiaNJW1NoU+qr/vzklHRCRTv+uTK+9APomGBbNM5m5v2YKvk5RryAt7RL6p6ZnLkAMfMTLTxHrymOMuclYNQ2StVeZ5/lfcM1N8EPFmq8+543xiVCawQUb/X6HfHAQ0DpOkvhnS+cLoKnFXhEOInuKT9egDTj2oVtNagUONq9vqt0wi1aYKJU7CPEC841vDMcw5gz4r6aYqvFvRx61MvruA="
